spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - PATCH
      routes:
        - id: authentication-microservice
          uri: lb://AUTHENTICATION-MICROSERVICE
          predicates:
            - Path=/api/v1/auth/**
        - id: products-microservice
          uri: lb://PRODUCTS-MICROSERVICE
          predicates:
            - Path=/api/v1/categories/**
        - id: products-microservice
          uri: lb://PRODUCTS-MICROSERVICE
          predicates:
            - Path=/api/v1/products/**
        - id: users-microservice
          uri: lb://USERS-MICROSERVICE
          predicates:
            - Path=/api/v1/users/**
        - id: orders-microservice
          uri: lb://ORDERS-MICROSERVICE
          predicates:
            - Path=/api/v1/orders/**
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: ${SERVER_PORT:8000}