spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: products-microservice
          uri: lb://PRODUCTS-MICROSERVICE
          predicates:
            - Path=/api/v1/products/**
          filters:
            - AuthFilter
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: false
server:
  port: ${SERVER_PORT:8000}